name: tiketBus
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  numberpicker: ^2.1.2
  intl: ^0.20.1
  shared_preferences: ^2.3.4
  webview_flutter: ^4.10.0
  printing: ^5.13.4
  pdf: ^3.11.1
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  open_file: ^3.5.10
qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
